### ISSUE TITLE
Customisable inventory loss for PvE

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#107]
Players and server management prefer the loss of items caused by PvE to be more severe than that caused by PvP.
We can distinguish two variants for server management to define:
1) Full inventory loss for death caused by PvE.
2) Partial inventory loss for death caused by PvE, but more severe than the loss set for PvP.
2a) Make players drop more of their armour and hotbar items after PvE death.
2b) Make players drop all of their passive inventory after PvE death, but the same number of items from their armour and hotbar slots.
2c) A combination of a and b.

In any case this requires distinction between cause of death, so a dedicated piece of code for all of the above options.

Before deciding which of the options are (un-)suitable for implementation, we better first get an idea of the code and gameplay implications and discuss them here.

I gave this high priority as I believe this to be an important feature for servers to consider. The risk and cost of dying by PvE is something that is fundamentally judged differently than the risk and cost of dying through PvP.

**Comment by CraftedMods** [comment]
Coding it is possible. And these losses only apply if `keepInventory` is enabled?

**Comment by AlteOgre** [comment]
Aye. With gamerule keepInventory false the entire partial inventory loss module would be disabled. Seems to make sense to me.

**Comment by CraftedMods** [comment]
Solution:
* Add a config option `Enable partial inventory loss for PvE` (default true)
* Add three config options: PvE item loss (for every of the three inventories) --> default as PvP
* Add a config option `Allow indirect PvP` --> Hits from hired units ans so on count as PvP --> default true
* Every death cause not caused by players or indirect PvP is handled with PvE
