### ISSUE TITLE
New command: pvpconfig

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#12]
Currently, the command `pvphelp` shows current configuration values. As I don't think that this is neither interesting for normal users (and spamms the chat) nor should they know about the server configuration, I suggest to create a new command `pvpconfig` which shows the current configuration entries. This command is only accessible for operators. The new command would also display currently enabled pvp combat logging handlers (if the PR is merged). Values like the warmup time could be interesting for users, but I don't think that this is really necessary, because the warmup time is already displayed if a player enabled pvp. But it could make sence to display them with `pvphelp`. ~~Furthermore the command could be used to manipulate the configuration data (parts of it that make sence) while the server is running. So `pvpconfig display` would display all configuration data; `pvpconfig set <property> <value>` would allow the manipulation of configuration data.~~ What do you think about this (@VulcanForge @AlteOgre  @Mahtaran)?

**Comment by AlteOgre** [comment]
Good thinking. Proposal seems to offer a decent way forward.
