### ISSUE TITLE
Extend proximity info with rough direction

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#125]
Players using the PvP Mode and hunted indicated the proximity info is only little helpful on large servers and effective tracking simply takes too long / too much effort.

Therefore it is proposed to add direction info. I propose to make that use 8 indicators: N, NE, E, SE, S, SW, W and NW. These can be derived by comparing coordinates and dependent on the differences between the coordinates in each direction the direction indicator can be determined.

Can be considered a high priority improvement as it significantly increases the usability of a mods feature to its users, and consequently the acceptance of the mod in the community.

**Comment by CraftedMods** [comment]
We cannot release it with `1.1.1-BETA`. But when working on `1.2.0-BETA` I'll work first on this, and then release a pre-release immediately after it's finished, so they don't have to wait that long for it.
