### ISSUE TITLE
Ensure in-game chat messages are gender neutral

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#127]
Some messages refer to 'he/him'. There are female players too, and possibly players of other gender types.

**Comment by AlteOgre** [comment]
Simple fix: We now have "WARNING: PvP is now enabled for playername because he entered an enemy biome" can simply become "PvP is enabled for playername upon entering an enemy biome". Shorter and gender neutral.

**Comment by Mahtaran** [comment]
Or “WARNING: PvP is now enabled for %playername% because they entered an
enemy biome”

**Comment by AlteOgre** [comment]
The message already is a warning, so the 'WARNING: ' part is superfluous. And not using 'he/she/they' is the safest way thinkable imo.

**Comment by Mahtaran** [comment]
It's nearly impossible to never use any of those though, and I don't think
anyone would be offended by "they" (because it's a gender neutral word).
Also, since all these messages will be configurable, a server owner could
change it if they wanted to.

**Comment by CraftedMods** [comment]
Not all messages will be configurable. There's no need for it. Only important ones.
