### ISSUE TITLE
Players with PvP Mode ON determine use of proximity info

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#134]
Provide a command '/pvp spy' for players with PvP Mode ON to toggle showing (ON) / not showing (OFF) the proximity info of themselves and other players with PvP Mode ON. If a player toggles it ON, his proximity is shown to all players with PvP Mode ON, and (s)he gets the proximity info of all other players with PvP Mode ON when using /pvplist.

This empowers players who prefer PvP, but wish to be hard to find at times, to decide for themselves if they can actively hunt and get actively hunted with assistance of player proximity info.

**Comment by CraftedMods** [comment]
This has to be configurable. Servers can enable or disable it.

**Comment by CraftedMods** [comment]
Is the radar enabled by default or not?

**Comment by AlteOgre** [comment]
Ah, forgot to mention that.

It should be disabled by default.

And another thing, important:
The word 'radar'shall no longer be used anywhere in our documentation or the mod. The proxomoity and direction info is a result of 'little birds' the player has, it's the extra, invisible, characters in the play that offer him/her info on the approximate whereabouts of a potential opponents. So instead of 'radar' use 'intelligence' to describe this feature. ;)

**Comment by AlteOgre** [comment]
Maybe create /pvp spy on/off, only available to players with PvP Mode ON.

**Comment by CraftedMods** [comment]
But renaming it to intelligence (at lest the config options) is not compatibile with a minor release. So I suggest that we call it radar until `2.0.0-BETA`.

**Comment by AlteOgre** [comment]
Ah, okay. No big deal. I'll start the makeover on wiki and other pages nonetheless. ;)

**Comment by CraftedMods** [comment]
The command the will function the following way:
* `pvp spy` simply toggles the intelligence.
* `pvp spy on` enables the intelligence
* `pvp spy off` disables the intelligence

**Comment by CraftedMods** [comment]
Should admins be able to override this for players? If yes, they also should be able to lock it for players, because otherwise on can just change it.

**Comment by AlteOgre** [comment]
Only for all. So a config option enabling/disabling this / forcing this on or off for all players is desirable. A per player override is neither necessary nor desirable imo.
