### ISSUE TITLE
Distinct warmup timers for ON->OFF and OFF->ON

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#135]
The warmup timer is mainly meant to prevent players from opting out of PvP quickly. Opting in PvP Mode should be less of a wait than opting out, especially as it should be possible when enemy biome overrides trigger the attention of 'home players' who would be willing to face the intruder. Consequently, it would be very helpful if the warmup timer for opting out can be set independently of the warmup timer for opting in. Indicative default values would become 30 seconds for opting in and 300 s for opting out.

**Comment by CraftedMods** [comment]
Duplicated with #48.
