### ISSUE TITLE
Prevent items tagged as [Soulbound] from dropping

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#149]
Several servers use either the SuffixForge serverside mod or a plugin to create lore items. One of the most valued aspects of those items is that they can get a tag called [Soulbound], which is meant to prevent the item from dropping upon death. Now the PvP Mode mod doesn't take this into account when determining which items to drop upon partial inventory loss, but it would be much appreciated if it did.

Here's a screenshot of a player file showing where and how this tag is registered:
![afbeelding](https://user-images.githubusercontent.com/21089897/42022750-5fccf06a-7abe-11e8-9bf2-e2648518ea40.png)

**Comment by CraftedMods** [comment]
I'm adding this as a SuffixForge compatibility module.

**Comment by CraftedMods** [comment]
Or to the other plugins/mods which add this name the tex also `SoulboundBool`?
