### ISSUE TITLE
Provide a feedback message upon usage of /pvpadmin

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#152]
We got this feedback from Veliks:
"btw, thoughts about allowing input in the /pvpadmin command? Right now it toggles but I'd like to see it change someone's pvp status to whatever is entered as input in the command after the username (ON/OFF). This is needed for e.g. minigames or events so I can have the server change peoples' status without having the chance of disabling it because they already have it toggled ON".
Seems a good and justified improvement.
Think of producing a response like this: "PvP Mode of playername changed to ON/OFF".

**Comment by CraftedMods** [comment]
I thought about this already. It's a small and important change, so I assigned it to `1.2.0-BETA`.
* `pvpadmin` toggles the mode
* `pvpadmin on` enables PvP
* `pvpadmin off` disables PvP
