### ISSUE TITLE
Default and extended enemy biome configs

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#153]
I gave the default some more thought and decided to create a more strict default file, in-line with the interpretation that only biomes where the home factions is in (near) full control should be defined as 'enemy biomes' for players with negative alignment with said faction. The old default is now renamed to 'extended' version. Both files now contain more textual information on all listed biomes so server management can more easily identify the biomes included in these files. I also create a map image, based on a sepia map of PB33.8, and used the colour codes of the factions on the LOTRmod wikia's Factions page to show the biomes used in the new default config.

New default:
https://www.dropbox.com/s/i8m3vszos07gtmu/pvpmode_lotr_enemy_biomes.txt?dl=1

Extended version (old default biomes, a little tweaked as well):
https://www.dropbox.com/s/v5a9x23ak72lbp5/pvpmode_lotr_enemy_biomes_extended.txt?dl=1

Map image for new default:
https://www.dropbox.com/s/kds6u4fojk0z2ae/PB338%20map%20enemy%20biomes.png?dl=1

It would be convenient for users if we would provide all three files.

I will already provide this info to the server owners who already use the mod, so they can make up their mind on which config to use.

Upon implementation of this issue, I will add the files and an explanation to the wiki here.

**Comment by CraftedMods** [comment]
It seems that all three links are the same one.

**Comment by AlteOgre** [comment]
Ye. Sowwy. Corrected.

**Comment by CraftedMods** [comment]
The last entry in the default configuration file for `ALL` is invalid, because there're no biomes specified. I commented it out (by putting a `#` before it).
