### ISSUE TITLE
help text with /pvplist: all players with pvp mode on

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#175]
The text now says it shows all hostile players, but that isn't correct. It shows all players with PvP Mode ON, or 'all players available for PvP'.

**Comment by CraftedMods** [comment]
By default ``pvplist` shows only the hostile players.

**Comment by AlteOgre** [comment]
Hostile and available for pvp are tow different things though.

**Comment by CraftedMods** [comment]
Yeah, hostile is inaccurate. Would changing "hostile players" to "players with PvP enabled" fix this issue?
