### ISSUE TITLE
Add /pvpadmin <player> <block|unblock>

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#195]
This command allows admins/command blocks to block/unblock the usage of `pvp` for a player. This is interesting for maps and such things.

**Comment by AlteOgre** [comment]
I don't quite see when this would be useful. Could you elaborate a bit more on this?

**Comment by AlteOgre** [comment]
I see. I wonder if this will be convenient in practise though. The more players join in an event, the more strenuous this will be for staff managing it. If it was up to me, I'd let the players deal with it. Easier to check a rule-breaker and act firmly in the case of an incident, than to prevent it with a lot more work and stress for staff.

**Comment by CraftedMods** [comment]
This is intended for command blocks.

**Comment by CraftedMods** [comment]
I think that this feature is not necessary anymore. With the planned override zones and so on all of this is achieveable too.
