### ISSUE TITLE
PvP free zones

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#200]
These can be biomes, rectangular or circular zones. All to be specified in a dedicated config file.

As noted in our issues list ex Fb group dd 20180602:
"o	Med Server defined areas
So, server management would appreciate some 'World Guard' like functionality that would define an area, either square or circular, that would override the PvP Mode ON and disable any PvP and hired unit combat?
I would expect servers to use forced PvP Mode OFF in: Shire and/or a spawn/market area and special (rp) (event) sites."
Server management can also use this feature to define temporary zones with PvP Mode forced ON, for wars and similar (roleplay) events.

**Comment by CraftedMods** [comment]
We even could create a World Guard compatibility module. But that would be another issue then.

**Comment by AlteOgre** [comment]
Edited first post to broaden scope. A logical step.

**Comment by CraftedMods** [comment]
For these temporary zones dynamic conditions could be defined. A default condition will be a countdown.

**Comment by CraftedMods** [comment]
Duplicated with #83. Please move all new things here to #83, then this issue will be closed.
