### ISSUE TITLE
Make the PvP toggeling configurable

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#219]

**Comment by AlteOgre** [comment]
Server management must be able to choose to either force PvP Mode ON or OFF for all players. Other, existing or new, override mechanisms should function normally, regardless this server setting.

**Comment by CraftedMods** [comment]
That is convered with #121. Also, I'll add `pvpadmin default <player>` which sets the PvP mode of a player to the default value. Players will have a new property `defaultForced` which indicated whether the default PvP Mode was forced onto a player. this is important for the release of new mod versions, because to example on EoA there're players with PvP enabled and disabled. Let's assume that the new default value for them is `ON`, all players with PvP disabled are forced to have it enabled. Then `defaultForced` is set to true. If then an admin would toggle the PvP mode of a player, `defaultForced` is still true, so the game knows that the non-default PvP mode then was changed by an admin.

**Comment by AlteOgre** [comment]
Yep. Good thinking. You'll make a good industrial control engineer.
