### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#24]
We should use [semver](https://semver.org/). A version is represented like this: `1.0.0-BETA.3`. The `.3` would be a pre-release version. For an non-pre-release the `.3` would be removed. What do you think about this?

**Comment by AlteOgre** [comment]
Eh, Okay, I guess.

**Comment by Mahtaran** [comment]
I'm always for Semantic Versioning

**Comment by CraftedMods** [comment]
I'll create a PR for it.
