### ISSUE TITLE
LOTR v34 update

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#247]
Update the following things:
* Biome id lists
* Enemy biome ME map

**Comment by AlteOgre** [comment]
Here are the updated biome list and config files for PB34.
[lotr_mod_biome_ids.txt](https://github.com/VulcanForge/pvp-mode/files/2353639/lotr_mod_biome_ids.txt)
[pvpmode_lotr_enemy_biomes.txt](https://github.com/VulcanForge/pvp-mode/files/2353640/pvpmode_lotr_enemy_biomes.txt)
[pvpmode_lotr_enemy_biomes_extended.txt](https://github.com/VulcanForge/pvp-mode/files/2353641/pvpmode_lotr_enemy_biomes_extended.txt)
I will work on that map later on. It will require me to redo the entire thing.

**Comment by AlteOgre** [comment]
I completed the new map image.
While doing that I also made a number of corrections in the other three files. Please use these newest versions as included in this post!
[lotr_mod_biome_ids.txt](https://github.com/VulcanForge/pvp-mode/files/2356840/lotr_mod_biome_ids.txt)
![pb341 map enemy biomes](https://user-images.githubusercontent.com/21089897/45155361-04b93180-b1db-11e8-843e-6b077b5a7862.png)
[pvpmode_lotr_enemy_biomes.txt](https://github.com/VulcanForge/pvp-mode/files/2356842/pvpmode_lotr_enemy_biomes.txt)
[pvpmode_lotr_enemy_biomes_extended.txt](https://github.com/VulcanForge/pvp-mode/files/2356843/pvpmode_lotr_enemy_biomes_extended.txt)
