### ISSUE TITLE
PvP-mode thinks entity is a player? Bug?

### ISSUE THREAD

**Issue by MilkMC** [VulcanForge/pvp-mode#250]
An Ocelot from the animal bikes mod got stuck in quagmire and when it took damage, it crashed the server. It looks like it may be a problem where pvp-mode thinks it's a player.
[crash-2018-09-06_22.12.20-server.txt](https://github.com/VulcanForge/pvp-mode/files/2359437/crash-2018-09-06_22.12.20-server.txt)

**Comment by CraftedMods** [comment]
I could reproduce the bug and fixed it. The changes have to be reviewed by another developer before we release an official version, but meanwhile you can use that version: http://www.filedropper.com/pvp-mode-131-beta1
