### ISSUE TITLE
Change command pvpcancel

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#26]
Currently, the only purpose of `pvpcancel` is to cancel the pvp warmup timer. Like `pvp`, the command only applies to the command sender. For this I think it would make more sence that we remove `pvpcancel` and move the functionality to the command `pvp` - logically this makes more sence to me, because the timer will be started with `pvp`. Canceling the timer then would be done via `pvp cancel`. If you agree (and if this actually makes sence, I don't know whether there are planns which require an own command) @AlteOgre , I would assign this to `1.0.0-BETA` and provide a PR for it.

**Comment by AlteOgre** [comment]
I can agree with this, but don't really see the need. Changing this doesn't have much implications in this stage, so if ever, do it asap.

**Comment by CraftedMods** [comment]
I did this mainly for logical reasons and the prevention of clutter. In future, we will have more commands, and having commands which also can be integrated into other commands makes this more clear for me. Also, the help menu of MC which is already large, won't be spammed that much (I know, one commands makes a big difference, but you know what I mean. If every mod tries to minimize the count of commands, it would become readable again).
