### ISSUE TITLE
Pvp command validation

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#31]
While working on the removal of `pvpcancel`, I noticed that the valdiation of commands was handled differently across the commands. Some commands are flexible and only check for the parameters they require - if there are additional parameters/keywords, they'll be ignored. Other commands (`pvpadmin`) are more strict - if there're more parameters then required, the command will fail. Also, what should we display if a command was used wrongly (the wrong parameters/keywords). Should we display a general purpose error message, usually the usage of the command (`pvp [cancel]`) in red, white, or another color, or a more detailed one? Or should this be flexible and display the general purpose message if the command itself was used in a wrong way, meaning that keywords were used wrongly or were missing, and if wrong parameters (like a player name, numbers, ...) were used than a specific message (example: `wrong player name`) would be displayed? I'm for the last one. This may seems petty, but we should arrange a standard for this, so that the mod is and feels uniform. Of course the priority of this is low, probably something for the next versions (`1.1.0-BETA` I suggest). If approved, I suggest the creation of a base class `AbstractPvpCommand` for all commands containing a protected function `help` which displays the pvp command usage message in red or whatever color we choose.

**Comment by AlteOgre** [comment]
Consistency is highly preferrable, both for user and coder. This is actually a good time to iron out such inconsistencies. Keep it simple for coders and discourage user lazyness is preferrable too. I'd rather have people get a general purpose error message and be forced to check the documentation we provide than them getting spoon-fed with in-game instructions we code for them, leading to precedencies and users having high expectations.
