### ISSUE TITLE
Hired unit attack interruption/prevention

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#38]
If a player with PvP Mode ON attacks a player with PvP Mode OFF, or his hired units, and this triggers a hired unit of the attacker to attack as well, the hired unit will remain attacking without causing any damage. That looks silly but can be very annoying as well. If possible, hired units of players with PvP Mode ON, should be unable to start attacking players with PvP Mode OFF and their hired units. This should get medium prio imo.

**Comment by CraftedMods** [comment]
Cause: The attack target is still set, but only the attack canceled. So the target has to be removed from the target task list.

**Comment by CraftedMods** [comment]
Can you reproduce this bug with the latest pre-release? The hired units shouldn't be triggered to attack a player or an unit of it. Never.

**Comment by AlteOgre** [comment]
Expected behaviour confirmed with internal patch 9. As soon as a player logs off however, hired enemy units will attack each other, regardless owners PvP Mode.

**Comment by CraftedMods** [comment]
This is covered with #113.
