### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#39]
The mod doesn't have an included changelog yet. I propose to start using and maintaining one from version 1.0.0-BETA onwards.

**Comment by CraftedMods** [comment]
We already have one (see https://github.com/VulcanForge/pvp-mode/blob/development/changelog.txt). But currently it won't be integrated into the built version.

**Comment by CraftedMods** [comment]
Should `1.0.0-BETA` already include it?

**Comment by AlteOgre** [comment]
Ikr. Many server staff are used to finding a changelog in a jar, when opening it. Many are used to go looking for one in a mod/plugin jar. For this version v1.0.0-BETA, I wouldn't include one yet. This is the first public beta after all. We may create a new changelog file and store the old one with a 'pre-BETA' tag/name?

**Comment by CraftedMods** [comment]
Why should we create a new one? The branches only contain the current ones (`development` the one of the current version in development/pre-release and `master` the one of the current release).
