### ISSUE TITLE
Proximity info for players with [GM1] or [FLY]

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#40]
Apparently players with PvP Mode ON still get proximity info in /pvplist even though their ability to pvp is blocked by GM1 or FLY mode. ~I think server owners would appreciate the option to disable proximity info whilst in GM1 or FLY mode, via server config.~

**Comment by CraftedMods** [comment]
I agree. I already looked at the code, adding this is easy. We should consider to add a general function `canDoPvp` or something like this to `PvpUtils` which determines in general if pvp for a player is possible, accounting the gamemode and the ability to fly and eventually other parameters too. This also reduced code duplucation and makes the code more readable. So, whoever will work on this feature, note what I wrote down above.

**Comment by CraftedMods** [comment]
Can be combined with #101.
