### ISSUE TITLE
1.1.0-BETA

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#43]
Currently, there's no development going on, because `1.0.0-BETA.1` has to be tested. As I currently have the time and motivation to work on the next version `1.1.0-BETA`, I would create a new branch `development-1.1.0-BETA` which is based on `development` and work on features for `1.1.0-BETA` (what the corresponding milestone contains). If `1.0.0-BETA` will be released, I'll merge the new branch with `development` and the development will be continued on `development`. Is this okay, or do we have to clarify some things regarding coordination and so on before the next version?

**Comment by AlteOgre** [comment]
Okay. I'll finish my screening of the Fb chat by tomorrow and then post all issues that still need to be addressed separately. We can use this thread to discuss the work at hand and new ideas and decide on priorities and which to target for which new release.

**Comment by CraftedMods** [comment]
Also, @VulcanForge wrote something about squashing all previous commits into one and reorganizing the development environment. I guess we should do this before any further development (but after the release of `1.0.0-BETA`.

**Comment by VulcanForge** [comment]
I accidentally deleted the outer directory in my development environment while installing a new OS on my computer. Assuming you have the repository in your own Eclipse workspace, feel free to reorganize for yourself. Also you may squash the commits as soon as you are ready.

**Comment by CraftedMods** [comment]
Ok, thanks for the reply. I'll reorganize the workspace after the release of `1.0.0-BETA` and post the new structure on here. Regarding squashing the commits: I would squash all commits up to `1.0.0-BETA` into one. For the future, every PR should contain one feature and thus one commit. So your history is more clear.

**Comment by CraftedMods** [comment]
Here's my workspace reorganization (https://github.com/CraftedMods/pvp-mode/tree/new_workspace). Feel free to provide feedback. If okay, we'll use this from `1.1.0-BETA` on.

**Comment by CraftedMods** [comment]
@AlteOgre Could you approve the PR #47 (so at least one person reviewed it)? I applied some formattings to the changelog.

**Comment by AlteOgre** [comment]
Here: https://www.dropbox.com/s/ilcn1l8sbrvieh4/Issues%20list%2020180602.docx?dl=1
All issues compiled from Fb chat, wiki thread and private communication with several server owners/staff/players.
Next: create new / update existing issues, prioritise, cluster and assign issues to new releases.

**Comment by AlteOgre** [comment]
I edited the document and added priority indications. I would love to have a next version by June 22nd with the tp blocking during combat and the partial inventory loss. Ideally, even with the biome-alignment conditional override. That date is the launch of the FA server, and they wish to start with the mod, including those 3 high prio features.

**Comment by AlteOgre** [comment]
That would suffice. And I'm okay with you assigning the issues. Will work most efficiently anyway.

**Comment by CraftedMods** [comment]
I've merged `development-1.1.0-BETA` with `development`. Also, Mahtaran will inform us what he did, I guess. I'll work on the refactorings and cleanup tasks first, and then on the partial inventory loss and the conditional overrides. But if anyone wants to do these, they can. Furthermore I suggest that we now release a pre-release after every major feature was added, to have development and testing parallel. Also, our testers can then focus on one specific feature.

**Comment by CraftedMods** [comment]
Someone (@Mahtaran or @VulcanForge) has to approve #57 before I can work on the PvPUtils improvement, because otherwise merge conflicts will occur.

**Comment by CraftedMods** [comment]
Please check #60, #62, #59  and especially #61. Before doing anything else @AlteOgre @VulcanForge @Mahtaran because there're some things that have to be clarificated.

**Comment by CraftedMods** [comment]
We're releasing a first official pre-release, `1.1.0-BETA.1`: http://www.filedropper.com/pvp-mode-110-beta1

**Comment by CraftedMods** [comment]
Second pre-release, `1.1.0-BETA.2`: http://www.filedropper.com/pvp-mode-110-beta2

**Comment by CraftedMods** [comment]
The version is now feature complete.

**Comment by CraftedMods** [comment]
Released the version: https://github.com/VulcanForge/pvp-mode/releases/tag/1.1.0-BETA
Now the github and LOTR wiki has to be updated.

**Comment by CraftedMods** [comment]
Ogre updated the wiki.Thanks! Now the work on `1.1.0-BETA` is finished.
