### ISSUE TITLE
SiegeMode mod compatibility

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#56]
The SiegeMode mod is increasingly in use in combination with the LOTRmod. The PvP Mode mod would ideally be fully compatible with the SiegeMode mod. This would imply that players should be able to join staged sieges/battles managed by the SiegeMode mod, regardless their PvP Mode and derived statuses. Joining and leaving sieges should not affect PvP Mode mod status, in any way.

This may be considered a medium-high priority aspect, possibly to be incorporated in v1.2-1.3.

For the time being, we assume players will toggle PvP Mode ON in order to join a SiegeMode mod event. The warmup and cooldown timers of the /pvp toggle will however cause some inconvenience for players.

**Comment by CraftedMods** [comment]
Compatibility with biome overrides: #62

**Comment by CraftedMods** [comment]
We also have to make the partial inventory loss compatible with the sieges.

**Comment by AlteOgre** [comment]
Aye. I thought I already reported that in an issue somewhere?

**Comment by CraftedMods** [comment]
I couldn't find it here.
