### ISSUE TITLE
Biomes  –  player  alignment  

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#62]
We  should  include  a  default  config  and  have  it  toggled  on/off  as  a  feature.  I  like  the  basic  idea  of  that  feature  and  would  support  it  defaulted  true.  That  'default  config':  list  of  alignment  condition  (#factions)  -  list  of  biomes  where  PvP  Mode  is  forced  ON.  The  default  list  will  only  use  biomes  that  can  realistically  be  considered  under  direct  control  by  a  faction  Examples:  
* DORWINION;  <  0;  112,140  
* MORDOR;  <  0;  5,6,50,51,52,53,135,136,137,138  
* HIGH_ELF;  <  0;  44,45,64,141

**Comment by CraftedMods** [comment]
Ideally, we consider #61 before implementing this.

**Comment by AlteOgre** [comment]
The complete, to be included, default input parameter list for this feature:

Faction name (for alignment command); value for criterium which forced pvp mode on, if player alignment smaller than value; biome identifier numbers where criterium is valid

HOBBIT; 0; 3,4,74,90,91,131,132
RANGER_NORTH: 0; 3,4,21,22,25,29,30,31,33,65,74,90,91,131,132,141
BLUE_MOUNTAINS; 0;47,87
HIGH_ELF; 0; 44,45,64,141
GUNDABAD; 0; 2,32,36,38,43,85,86,129,143
ANGMAR; 0; 13,21,22,26,42,55,65,71
WOOD_ELF; 0; 14,66,79,80
DOL_GULDUR; 0; 15,46,48,49,119
DALE; 0; 66,139
DWARF; 0; 11,15,32,78,85,86
GALADHRIM; 0; 9,10,39
DUNLAND; 0; 23,41,72
URUK_HAI; 0; 16,60,72
FANGORN; 0; 24,57,60,67
ROHAN; 0; 1,57,61,130
GONDOR; 0; 7,8,18,19,28,56,57,58,59,62,68,69,76,82,93,114,147,148,151,152,153,154,155
MORDOR; 0; 5,6,12,17,34,49,50,51,52,53,69,70,81,135,136,137,138
DORWINION; 0; 112,140,160
RHUN; 0; 157,158,159,160
NEAR_HARAD; 0; 28,96,99,101,106,108,120,128,146,149,151
MOREDAIN; 97,105,121,122
TAUREDAIN; 100,103,109,110,123
HALF_TROLL; 107

Biome identifiers not used:
20 dummy
27 Old Forest
35 The Sea
37 Meneltarma
40 Forodwaith
54 dummy
63 Lake
75 Swanfleet
77 Minhiriath
83 Island
84 Forodwaith Mountains
88 Northlands
89 Northern Forests
92 Forodwaith Glacier
94 Beach
95 Gravel Beach
98 Harad Mountains
102 dummy
111 dummy
113 Tolfalas
115 Rhûn
116 Rhûn Forest
117 Red Mountains
118 Red Mountains Foothills
124 Far Harad Cloud Forest
125 Far Harad Bushland
126 Far Harad Bushland Hills
127 Far Harad Mangrove
133 Near Harad Red Desert
134 Far Harad Volcano
142 dummy
144 Forodwaith Coast
145 Far Harad Coast
150 White Beach
156 Drúwaith Iaur
161 Tol Rhúnaer
162 Eryn Rhúnaer
163 Last Desert
164 Mountains of the Wind
165 Foothills of the Wind

Info derived from code of PB33.8, as reported here:
https://lotrminecraftmod.wikia.com/wiki/Regions#List_of_Regions

**Comment by AlteOgre** [comment]
Proposal by EoA staff, to add to the default: make every player get PvP Mode forced ON on Meneltarma (biome #37). Additional condition to ensure that could be:
ALL; 66666; 37

**Comment by CraftedMods** [comment]
Should the biome overrides really be "forced" (so players can have the pvp mode `OFF` in these enemy biomes), or should admins be able to override this?

**Comment by AlteOgre** [comment]
The intent is to have the PvP Mode forced ON as soon as a player enters an 'enemy-designated' biome, which is determined by the players alignment, a criterium value and a preset list of biomes where this should happen if condition is met. As borders can be quite fuzzy, it may not make sense to make this effective immediately upon entering a chunk/block with a different biome id that triggers the override. But, a delay may work in a similar way and cause a lot of apparently unneeded switches when a player continuously crosses biome id borders. I think that indeed, the best way would be to have a configurable interval time (order of magnitude 100-500 ticks: ~100-500 blocks travel time on fastest horse) after which a check is done, and effectuate the override without any delay. Beng! With chat message: 'Player A just got PvP forced ON while entering enemy territory!', unless player A already had PvP Mode ON ofc. In that case there will be no override nor message. And indeed, warmup timers have to be cancelled immediately, and reset, but cooldown timer progress should not be affected. When leaving enemy biome, player A will automatically get his former PvP Mode status. Does that cover all? Any other thoughts?

**Comment by CraftedMods** [comment]
Should this only cover ME biomes, or be applicable to MC biomes too (alignment?)? This is an important decision, because this decides whether this will be in the compatibility module or in the general codebase.

**Comment by AlteOgre** [comment]
As far as I can tell there are no other mods that work with alignment. But from a server owner viewpoint, it may be very interesting to use this feature in other worlds as well, and with other biome adding mods too. Imagine the possibility to force PvP Mode ON in different Thaumcraft biomes, or in various biomes of BoP. Another thought is that any area deisgnated as 'Siege' area by the SiegeMode mod, should not lead to the default intervention by this PvP Mode mod feature. Entry in SiegeMode mod areas must lead to forced PvP Mode ON independent of alignment or biome. Finally, server management may designate areas as 'safe zones, where PvP Mode should be overriden to OFF. These may be designated by other mods or plugins. So I think adding this to the compatibility module would be wisest and we have enough reason to do so.

**Comment by CraftedMods** [comment]
I'll do it this way: The general codebase support conditional overrides, checking a configurable period of time for specific conditions. If such a condition applies, the PvP mode of this condition is forced. These conditions will be priorized - the condition with the highest priority applies. This way we can have siege zones in hostile biomes. The compatibility modules then can set such conditions - to example the LOTR module sets the biome conditions.

**Comment by CraftedMods** [comment]
For the configurable override check interval I have the following bounds (all values in seconds):
- Min: -1 (disable overrides)
- Max: 60
- Default: 10
If the interval is set to zero, the checks will be executed every tick.

**Comment by CraftedMods** [comment]
Also, feel free to open issues for the additional override conditions you've mentioned: Overrides for vanilla biomes, and for spawns or "safe" zones. The issue for the SiegeMode compatibility already contains a reference to this issue, so the person who will work on it will also take the overrides into account.

**Comment by CraftedMods** [comment]
Also, should the overrides optionally (which means configurable) only apply to the spheres of incluence of these factions?

**Comment by AlteOgre** [comment]
Yes, safe biomes where PvP Mode is forced OFF should be configurable. And PvP Mode forced ON in Spheres of Influences of enemy factions as well. I think forced PvP Mode ON should either be defined per biome or per SoI, not both. Server can select which method, define alignment criterium, and only for the biome method either use the default list or customise it. Safe zones/biomes should work independent of the forced-ON zones, so that should prevail over them. Two additional issues to be created I guess.

**Comment by CraftedMods** [comment]
Could you create these issues? Also, assign them to the version you want to have them. This issue only covers the enemy biome list, but the framework created with it makes it easy to implement these things as additional conditions.

**Comment by CraftedMods** [comment]
Could you also document the enemy biome list?
I suggest you to add a header explaning the format, also it should include these things:
- Comments cover a whole line, which must start with `#`
- Blank lines, spaces and comments will be ignored
- If the file (in the config folder) is deleted, it'll be recreated
- Unknown biomes/factions/alignment values lead to a warning in the logs
- Entries which couldn't be processed will be ignored

**Comment by CraftedMods** [comment]
Also, I found a mistake in the config file: The entry for `RANGER_NORTH` contains a `:` instead of a `;`.

**Comment by AlteOgre** [comment]
I'll provide Notepad++ created files with the requested list info. Thanks for the format requirements.

**Comment by CraftedMods** [comment]
If duplicated entries were found, the first discovered entry will be used.

**Comment by CraftedMods** [comment]
Players in `GM_1` or ``FLY` mode will be excluded from the condition checks. Only when they cannot fly anymore or are in survival they'll be taken into account.

**Comment by CraftedMods** [comment]
The warmup timer will be canceled after the override. The command `pvp` and `pvpadmin` cannot used for a player whose PvP mode is overridden.

**Comment by AlteOgre** [comment]
Saw an oops in my biomes list:
For ME (DIM-100) the biome with ID 0 is River. Utumno also has ID 0, but for DIM-101.
In what way shall we best note this in the config?
Or shall we not include any other dimensions except DIM-100 yet, for 1.1.0-BETA?

I'm working on the default config atm, and I will create a separate txt file with all ME biome ID's for reference.

**Comment by CraftedMods** [comment]
I think it's the best to support additional dimensions with the next versions.

**Comment by AlteOgre** [comment]
Here's the default config.
https://www.dropbox.com/s/i8m3vszos07gtmu/pvpmode_lotr_enemy_biomes.txt?dl=1
Hope I got that format right.
Other file is 30% complete, silly text editing work.

**Comment by CraftedMods** [comment]
Could you also explain these things I wrote in the comment above? So that the users know what they are allowed to do and what not.

**Comment by CraftedMods** [comment]
Also, where should the biome id file be? In the config folder, in the main folder, in a custom PvPMode folder?

**Comment by AlteOgre** [comment]
Config will be fine I think. Please add 87 to GUNDABAD. Forgot that one.
If you have the time, go ahead and add that description to the config. I have several things on my plate atm. xD

**Comment by CraftedMods** [comment]
Sure.

**Comment by CraftedMods** [comment]
I'll put the biome id file in the main directory, because otherwise people think that they can change biome ids.

**Comment by AlteOgre** [comment]
There:
https://www.dropbox.com/s/i8m3vszos07gtmu/pvpmode_lotr_enemy_biomes.txt?dl=1

**Comment by CraftedMods** [comment]
This is the config file template.
