### ISSUE TITLE
Improved combat logging

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#7]
What do you think about CSV combat logs? Considering the sheer mass of log entries which will be collected, it could be better to save the logs in the CSV format, which means that server admins can open the file with a tool like Excel and sort/filter the informations contained in it like they want. Also it is better to  either save the full data or - better - rotate the log files each day, which means that every day a new file will be created with the current date contained in the file name. Of course this would be configurable.
So, what do you think about it? If you want, I'll gladly provide a PR for this (unless you want to work on this by your own).

**Comment by Mahtaran** [comment]
I'm all for it. Maybe we'd later add a function for logging to SQL (MySQL and SQLite) and plain text.

Where you planning on using a third part library (if you were, OpenCSV?) or are you going to write your own parser?

Maybe you could start working on the backbone of the system (the functions to log it, file loading/saving etc.), and I'll do the actual logging itself and finish your work once I get home from Rome.

BTW, do you maybe want to be added to the developer chat on Facebook? If so, contact me please (Just search for "Mahtaran" on FB)

**Comment by CraftedMods** [comment]
1. SQL? Which server owner runs a database? No, logging to a database is definetely not necessary. Not even to Derby. 
2. For this we don't need a parser. Do you know what a parser is? A parser would read an already existing CSV file and extract the content of it into something. We only want to write data to a CSV file. As CSV is extremely simple, we don't need a third-party libary. Simply writing the data to a file, separated by   a common separator (like , or ;) does the job. To example, we could write "04.05.2922; Player1234; Player5678" to the logs, every entry is then a column of a table. CSV is as simple as this.
3. I don't really see a reason why a such simple task as this should be splitted. I can do this within ten minutes (excluding testing).
4. I don't use Facebook.

**Comment by Mahtaran** [comment]
1. Well, I know that I for one use MariaDB for nearly all my logs. Also, I don't think you need any dependencies for using SQL (MysqlDataSource) other than JDBC2, which is included by default nowadays.
2. Oh sorry completely overlooked it
3. Well what are you waiting for? 😉
4. Okay

**Comment by CraftedMods** [comment]
1. Yes you need. JavaSE doesn't include a JDBC driver for MySQL - and also not for MariaDB. So you need an external connector (a JDBC driver). JavaSE only contains the general interface for all drivers - but the actual implementation is not included in the JDK/JRE. 
3. The whole point of this issue is to discuss this with @VulcanForge, to see whether something like this is planned and to see whether he is working on something like this or has ideas for it - I don't create pull requests if I don't know what's going on. Communication is essential for this.

**Comment by Mahtaran** [comment]
Oh yeah, you do need the database driver to be installed. But I assume that if you enable MySQL in the config, you have MYSQL installed.

And I guess we'll wait for Vulcan

**Comment by Mahtaran** [comment]
Also please note that you don't need a separate driver for MariaDB as it's a fork of MySQL, not that it matters

**Comment by CraftedMods** [comment]
I've never said this. And now, please, back on topic.

**Comment by VulcanForge** [comment]
Data recording is totally out of my experience. Build a system and demonstrate it for AlteOgre. If he likes it I'll merge the pull request (barring any huge issues which I am not forseeing at the moment).

**Comment by CraftedMods** [comment]
Ok, thank for the reply. I'll talk with Ogre.

**Comment by AlteOgre** [comment]
Good proposal afaic. We cannot assume SQL is used by all servers, so we'll have to go for something lean and broadly applicable. It could be nice if SQL would be supported, but only for the long term: a 'nice to have feature', so to speak. Therefore I agree with the basic view and proposal of CraftedMods (weird name that ...).

**Comment by AlteOgre** [comment]
Sounds good. But in due time. I think we best focus on getting that lean and sufficient combat event logging by CraftedMods going and in the meantime VF focuses on debugging and merging other contributions, and Maht/Aj could best work on 1) the blocking of any teleports after initiation of a combat event (if not also covered by CM), and 2) the conditional overrides we discussed in the Fb group chat.

**Comment by CraftedMods** [comment]
I've created a general interface for pvp logging. The logging is now done by logging handlers (classes implementing the interface CombatLogHandler) - there can be several handlers, but only one which is currently active (the user defines the handlers with the configuration file - if he uses 'none' as handler, pvp logging will be disabled). Currently there is one logging handler - the default one which was created by @VulcanForge . I applied some modifications to it. The CSV handler and every other handler you can imagine will be implemented using this interface. The handlers are known at compile time - they'll be registered manually in PvpCombatLog with an unique name. Personally I dislike the "static" style used in PvpCombatLog - I suggest to make the whole class non-static and addind an instance of it to a field in PvpMode (but currently this is not that important). Should we support several currently active handlers acting concurrently, or do you think one active handler is sufficient? Also note that I didn't document the logging handler API - I'll do this if it's finished. So, @Mahtaran , I'm waiting for your feedback regarding the **API** (which consists of all public members of PvpCombatLog and CombatLogHandler), in case you still want to create a SQL handler. When you're going to create the SQL handler, you'll be using this API. If you want to apply modifications to the API, create a PR for this branch: https://github.com/CraftedMods/pvp-mode/commits/pvp_logging

**Comment by Mahtaran** [comment]
Looks pretty good! I might make a PR with an annotation handler (So there's only need for 1 registration method, and it'll become modular so other plugins/mods can maybe register their own logging system) and one with the ability to use multiple logging handlers (just some boolean entries in the config), and when you get it done I'll work on the SQL logging.

**Comment by CraftedMods** [comment]
I already did something like this for the NEI Plugin to support dynamic recipe handlers. If your SQL handler needs external dependencies, we'll need something like this, because we cannot package a JDBC driver with the mod.

**Comment by Mahtaran** [comment]
Yeah exactly

**Comment by CraftedMods** [comment]
So, I guess you've seen the changes I've made to the API. If you say that you can use this as a base for future handlers, I'll start with the CSV handler.

**Comment by CraftedMods** [comment]
I've finished the logging. I also improved the default logging handler and added support for logging file rotation. Here's a test version: http://www.filedropper.com/pvp-mode-10pre1
Maybe @AlteOgre is interested to test it.

**Comment by CraftedMods** [comment]
Sorry, I didn't say that some things changed: There are two pvp logging handlers: A default one (enabled by default, surprise) and the CSV handler. You can enable one, no or both handlers. The data won't be stored at pvpmode.log (this is an old file), but in the directory combat/default in your logs folder. This is because of the log file rotation - if each handler has it's own folder, the log file management is more clear. And your logs say that the default handler was initialized.

**Comment by AlteOgre** [comment]
Ah, lol. There it is.
[pvpmode_latest.log](https://github.com/VulcanForge/pvp-mode/files/1996620/pvpmode_latest.log)

**Comment by CraftedMods** [comment]
Perfect. And as you can see, the default logging method pretty confusing und unordered. So the CSV handler really improves the readability of the data. Also, the CSV separator can be configured - the default one is `;`.

**Comment by AlteOgre** [comment]
Aye. Saw that in the adjusted config.

**Comment by CraftedMods** [comment]
So are there any suggestions on how to improve the logging? Otherwise I would create a PR.

**Comment by AlteOgre** [comment]
Eh ... replace "an unit" with "a (hired) unit"? Can't think of anything else atm.

I'm pondering the registration of the beginning and the end of a combat event, but I feel that just won't be that simple ... many possible combat scenario's with 2 or more players (incl. hired units) involved cross my mind. Pffff ...

How can one enable/disable the handlers?

**Comment by CraftedMods** [comment]
I've adjusted the default logging message with bc208e5234c2ec95c7ca69497e8244a19832969f.
The beginning/end of combat events is definetely complicated. I guess it's possible, probably requiring some configuration data which can be used as a reference to determine whether a fight starts/ends (something like a timer which says after which time with no attacks a fight is considered as finished). But I would say that this is a feature for a version in the near/"middle" future.
You can enable or disable handlers by adding/removing their names to/from the configuration file.

**Comment by AlteOgre** [comment]
Aye. That should do for 90% of scenarios. No use striving for perfection I think.

Ah, yeah, now I see it in the config. Blurry vision here, sorry.

**Comment by AlteOgre** [comment]
Did some more testing, with various weapons and a bit of armour. Used both default and csv logging. There seems to be a double registration of all attacks. Can you check and correct that please? Note that the csv storage is much leaner and slicker=convenient imo.
[pvpmode_latest.log](https://github.com/VulcanForge/pvp-mode/files/1997533/pvpmode_latest.log)
Can't upload the *.csv here btw, as that type is not supported by GitHub.

**Comment by CraftedMods** [comment]
Did you run the mod on a "real" server or as a LAN world. Pvp Mode is supposed to be a server-side mod, if it's installed on a client this may lead to the double registration of the pvp events.

**Comment by CraftedMods** [comment]
I've prbably found a fix for this. But the issue is serious, and could impact performance, because some performance-constly functions will be invoked more often than required. See #23

**Comment by CraftedMods** [comment]
Furthermore, the logged damage is the damage which was dealt, not the damage which was actually applied to the victim.

**Comment by CraftedMods** [comment]
Here's another testing version: http://www.filedropper.com/pvp-mode-10pre2

**Comment by AlteOgre** [comment]
Tested.
[pvpmode_latest.log](https://github.com/VulcanForge/pvp-mode/files/1998161/pvpmode_latest.log)
Double registration is still a thing in the default/simple handler. Maybe because of my LAN setup?
The csv handler nicely only registers all attacks once.
![afbeelding](https://user-images.githubusercontent.com/21089897/39964226-379541f4-5680-11e8-8de2-32dfe51be3cf.png)
[fml-server-latest.log](https://github.com/VulcanForge/pvp-mode/files/1998162/fml-server-latest.log)
Didn't notice any other oddities.

**Comment by CraftedMods** [comment]
I renamed the handler `default` to `simple`. So currently in your configs there's a handler `default` - the mod doesn't recognize it (logs: `The pvp combat logging handler "default" is not valid.`). So actually the data in latest.log were the data from the test before.

**Comment by AlteOgre** [comment]
Ah, right.

**Comment by AlteOgre** [comment]
The config still mentioned default btw.

**Comment by CraftedMods** [comment]
Forge doesn't recreate the config entries. You've to delete the file so it can be recreated.

**Comment by CraftedMods** [comment]
Should we include the pvp loggin into `1.0.0-BETA` as it is, or do you want to test it more? Otherwise we can merge #18 after @Mahtaran finally reviewed it (because of the contribution guidelines).

**Comment by CraftedMods** [comment]
Closed with #18
