### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#9]
Currently, it seems that we're using Java 6. I suggest to use Java 8, because it contains features (the extended date and time API, lambda expressions, diamond operator (Java 7), ...) which are useful and more efficient. Are there any reasons for it @VulcanForge ? If we change to Java 8, you'll have to add two entries to your build.gradle. I can provide a PR if you want.

**Comment by VulcanForge** [comment]
Please do.

**Comment by CraftedMods** [comment]
No, you don't need (see https://github.com/diesieben07/SevenCommons/blob/master/build.gradle#L28-29).

**Comment by CraftedMods** [comment]
Will be closed with #10

**Comment by Mahtaran** [comment]
Oh, nevermind what I said, good job 👍🏻
