### ISSUE TITLE
Make bypassing the partial inventory loss harder

### ISSUE THREAD

**Issue by CraftedMods** [VulcanForge/pvp-mode#92]
Partial  inventory  loss  may  be  by-passed  by  quickly  moving  items  from  affected  slots  before  a  player  dies.  This  may  be  countered  in  two  ways:  
1)  block  use  of  Shift-clicking  when  in  inventory  mode  during  a  combat  event.  
2)  Make  sure  the  partial  inventory  loss  code  is  smart  enough  to  compensate  for  empty  slots  in  the  armour  and  active  inventory  and  chooses  the  first  available  armour  and  weapon  items  it  finds  in  the  passive  inventory  in  case  there  are  not  enough  items  in  the  armour  slots  respectively  active  inventory.

**Comment by AlteOgre** [comment]
Blocking of Shift-clicking has high prio.

**Comment by CraftedMods** [comment]
I suggest the following extensions:
* Introduce a third option: main inventory loss (a configurable amount of items lost from the main inventory)
* If too less items are found in the hotbar/armor slots, the game will look in the main inventory for appropriate items
* These will be priorized: 
  * If items in the armor slots are missing, the game looks for armor in the main inv (if no armor was found, then the game won't search for additional items)
  * If items in the hotbar are missing, the game first looks for weapons, draughts and so on in the main inv
      * Therefore the items in the main inv will be priorized by the game (only for the hotbar loss)
      * This can be extended via compatibility modules

**Comment by CraftedMods** [comment]
By their Java classes.

**Comment by AlteOgre** [comment]
Ah right! Could have know that lol.
