### ISSUE TITLE
Config option to enable/disable partial inventory loss.

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#96]
Some server management may want to have full inventory loss, and others will 'feel better' when they can fully disable it in the config. It's not urgent to have this, but yes, it may be appreciated by users.
See #94 for earlier discussion.

**Comment by CraftedMods** [comment]
Should it be enabled by default?

**Comment by AlteOgre** [comment]
I'd say yes, as it is an essential part of the approach and intent we have with the mod: To empower players and encourage pvp.
